import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import type { Runtime } from "../runtime";

export const SCRIPT_TEMPLATE = (name: string) => `/**
 * ${name} — generated by Sailor (/new-script). Uses the official Fiber TypeScript SDK.
 *   npm i @fiberai/sdk
 *   FIBER_API_KEY=sk_live_… npx tsx scripts/${name}.ts --dry-run
 * Conventions: key from env (never hard-code), log chargeInfo, poll async jobs ≥ 30s apart,
 * confirm before paid loops, --dry-run prints estimates only.
 */
import { getOrgCredits, peopleSearch } from "@fiberai/sdk";
import { createInterface } from "node:readline/promises";

const apiKey = process.env.FIBER_API_KEY ?? process.env.FIBERAI_API_KEY;
if (!apiKey) throw new Error("Set FIBER_API_KEY");
const DRY_RUN = process.argv.includes("--dry-run");

async function confirm(question: string): Promise<boolean> {
  if (process.argv.includes("--yes")) return true;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const a = await rl.question(\`\${question} [y/N] \`);
  rl.close();
  return /^y/i.test(a);
}

async function main() {
  const credits = await getOrgCredits({ query: { apiKey: apiKey! } });
  const available = (credits.data as any)?.output?.[0]?.available;
  console.log(\`Fiber credits available: \${available}\`);

  const pageSize = 25;
  const estimate = pageSize * 1; // peopleSearch: 1 credit per profile returned
  if (DRY_RUN) return console.log(\`[dry-run] would spend up to ~\${estimate} credits\`);
  if (!(await confirm(\`Spend up to ~\${estimate} credits?\`))) return;

  const { data, response } = await peopleSearch({
    body: { apiKey: apiKey!, pageSize, searchParams: { jobTitleV2: { anyOf: [{ type: "term", term: "Head of RevOps" }] }, country3LetterCode: { anyOf: ["USA"] } } },
  });
  if (response.status !== 200) throw new Error(\`peopleSearch failed: HTTP \${response.status}\`);
  console.log("chargeInfo:", JSON.stringify((data as any)?.chargeInfo));
  for (const p of (data as any)?.output?.data ?? []) console.log(p.name, "—", p.headline);
}

main().catch((e) => { console.error(e); process.exit(1); });
`;

export function registerScriptCommands(pi: ExtensionAPI, rt: Runtime): void {
  pi.registerCommand("new-script", {
    description: "Scaffold a Fiber SDK automation script: /new-script <name>",
    handler: async (args, ctx: ExtensionContext) => {
      rt.init(ctx);
      const name = (args ?? "").trim().replace(/[^\w-]/g, "_") || "fiber_script";
      const dir = join(rt.cwd, "scripts");
      mkdirSync(dir, { recursive: true });
      const file = join(dir, `${name}.ts`);
      if (existsSync(file)) { ctx.ui?.notify(`${file} already exists.`, "warning"); return; }
      writeFileSync(file, SCRIPT_TEMPLATE(name));
      const msg = `Created ${file}. Run: FIBER_API_KEY=… npx tsx scripts/${name}.ts --dry-run  (switch to /mode engineer to let Sailor edit & run it).`;
      if (ctx.hasUI) ctx.ui.notify(msg, "info"); else console.log(msg);
    },
  });
}
